# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TwilioSms < Formula
  desc ""
  homepage "https://github.com/syndikat7/homebrew-tools"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/syndikat7/twilio-sms/releases/download/v0.0.3/twilio-sms_Darwin_arm64.tar.gz"
      sha256 "8897de33d165850e889e452c46be4df9fd4e93eecfa7ce139f668de24fb5a88b"

      def install
        bin.install "twilio-sms"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/syndikat7/twilio-sms/releases/download/v0.0.3/twilio-sms_Darwin_x86_64.tar.gz"
      sha256 "09d7967d680d22f978dc7eb29e1090fe1260668dca890228d24076c6427c2641"

      def install
        bin.install "twilio-sms"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/syndikat7/twilio-sms/releases/download/v0.0.3/twilio-sms_Linux_arm64.tar.gz"
      sha256 "4fb9d175b1c52b0baca2297479582f3d1c1a250f6cfd2ed4348bef60b4a3477c"

      def install
        bin.install "twilio-sms"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/syndikat7/twilio-sms/releases/download/v0.0.3/twilio-sms_Linux_x86_64.tar.gz"
      sha256 "a4b06a995011c7ee7266af568ea6781b4fa66895f0bafec9af0308bb37cd0ddd"

      def install
        bin.install "twilio-sms"
      end
    end
  end
end
